In [23]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [24]:
train_images.shape

(60000, 28, 28)

In [25]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [26]:
test_images.shape

(10000, 28, 28)

In [27]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [28]:
# Network architecture
from keras import models
from keras import layers

In [29]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [8]:
# Compilation step
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

# Preparing the image data
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32')/255

In [9]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

# Fitting the data
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 85us/step - loss: 0.2595 - acc: 0.9252
Epoch 2/5
60000/60000 [==============================] - 5s 86us/step - loss: 0.1042 - acc: 0.9694: 0s - loss: 0.1062 - ac
Epoch 3/5
60000/60000 [==============================] - 6s 95us/step - loss: 0.0694 - acc: 0.9792
Epoch 4/5
60000/60000 [==============================] - 6s 98us/step - loss: 0.0494 - acc: 0.9851
Epoch 5/5
60000/60000 [==============================] - 5s 90us/step - loss: 0.0373 - acc: 0.9894


In [10]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 57us/step
test_acc: 0.9789


In [ ]:
# 3D Tensors
import numpy as np

In [14]:
x = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]]])
print(x.shape)
print(x.ndim)

(3, 3, 5)
3


In [33]:
# Displaying the fourth digit
# digit = train_images[4]
# import matplotlib.pyplot as plt
# plt.imshow(digit, cmap=plt.cm.binary)
# plt.show()

# Manipulating tensors in Numpy

my_slice = train_images[10:100]
print(my_slice.shape)

my_slice2 = train_images[:, 7:-7, 7:-7]
print(my_slice2.shape)

(90, 28, 28)
(60000, 14, 14)


In [46]:
# B&W images: 128, 256, 256, 1
# Color images: 128, 256, 256, 3

x = np.array([[0,1], [2,3], [4,5]])
print(x.shape)

(3, 2)


In [45]:
x = x.reshape((6,1))
print(x)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
